function onCreatePost()
  setProperty('scoreTxt.visible', false)
  setProperty('timeBar.color', getColorFromHex('18C714'))
  setProperty('timeTxt.color', getColorFromHex('18C714'))
end
function onCreate()
  makeLuaText('scorestuff', 'Score:' .. score .. ' | Ph0ne Br3aks:' .. misses .. ' | Rating:' .. ratingName .. ' | % ' .. rating, getProperty('healthBarBG.width'), 400, 680)
  makeLuaText('watermark', getPropertyFromClass('PlayState', 'SONG.song') .. ' - Corrupt Engine', getProperty('healthBarBG.width'), 0, 700)
  setTextSize('scorestuff', 20)
  setTextColor('watermark', '18C714')
  setTextColor('scorestuff', '18C714')
  addLuaText('watermark')
  addLuaText('scorestuff')
  makeLuaText('combo', 'Combos: ' .. getProperty('combo'), getProperty('healthBarBG.width'), 0, 480)
  makeLuaText('sick', 'Sicks: ' .. getProperty('sicks'), getProperty('healthBarBG.width'), 0, 520)
  makeLuaText('good', 'Goods: ' .. getProperty('goods'), getProperty('healthBarBG.width'), 0, 540)
  makeLuaText('bad', 'Bads: ' .. getProperty('bads'), getProperty('healthBarBG.width'), 0, 560)
  makeLuaText('shit', 'Shits: ' .. getProperty('shits'), getProperty('healthBarBG.width'), 0, 580)
  setTextColor('combo', '18C714')
  setTextColor('sick', '18C714')
  setTextColor('good', '18C714')
  setTextColor('bad', '18C714')
  setTextColor('shit', '18C714')
  addLuaText('combo')
  addLuaText('sick')
  addLuaText('good')
  addLuaText('bad')
  addLuaText('shit')
end
function onUpdate(elapsed)
  setTextString('scorestuff', 'P0ints:' .. score .. ' | Miss3s:' .. misses .. ' | R4ting:' .. ratingName .. ' | % ' .. rating)
  setTextString('watermark', getPropertyFromClass('PlayState', 'SONG.song') .. ' - 7/14/2006', getProperty('healthBarBG.width'))
  setTextString('notehit', 'Total Notes Hit: ' .. getProperty('combo'), getProperty('healthBarBG.width'))
  setTextString('sick', 'Sicks: ' .. getProperty('sicks'), getProperty('healthBarBG.width'))
  setTextString('good', 'Goods: ' .. getProperty('goods'), getProperty('healthBarBG.width'))
  setTextString('bad', 'Bads: ' .. getProperty('bads'), getProperty('healthBarBG.width'))
  setTextString('shit', 'Shits: ' .. getProperty('shits'), getProperty('healthBarBG.width'))
end